services:
  - type: web
    name: cerro-largo-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
